module.exports = {
  URL_API: process.env.URL_API,
  URL_COMMON: process.env.URL_COMMON,
  VAPID_KEY: process.env.VAPID_KEY,
  URL_FILE: process.env.URL_FILE,
  URL_WEB_FRONT: process.env.URL_WEB_FRONT,
  FIREBASE_API_KEY: process.env.FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN: process.env.FIREBASE_AUTH_DOMAIN,
  FIREBASE_DATABASE_URL: process.env.FIREBASE_DATABASE_URL,
  FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET: process.env.FIREBASE_STORAGE_BUCKET,
  FIREBASE_SENDER_ID: process.env.FIREBASE_SENDER_ID,
  FIREBASE_APP_ID: process.env.FIREBASE_APP_ID,
  FIREBASE_MEASUREMENT_ID: process.env.FIREBASE_MEASUREMENT_ID,
  URL_SOCKET: process.env.URL_SOCKET,
  URL_ADMIN: process.env.URL_ADMIN
};
